### ISSUE TITLE
가게 재고 보여주기

### ISSUE THREAD

**Issue by hmxb** [emartFresh/emart-fresh-back#125]
## Description 🗞️📕
가게 재고 보여주기
프론트에서 가게 id와 상품명을 주면 재고를 보여줌

## Page 🖥️
storeController

## To-Do ✔️
- [ ] 가게id로 가게를 찾고
- [ ] 상품명으로 product(list)를 끌고와서
- [ ] 찾은 가게에서 product의 재고를 + 해서 반환함
