### ISSUE TITLE
토큰 유효성 관련

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh-back#18]
## Description 🗞️📕
액세스 토큰이 만료되었을 떄, authentication 객체에 접근하면 재발급 처리가 제대로 되는지 확인하고 그렇지 않다면 에러 핸들링을 통해 올바르게 처리해야합니다.

## To-Do ✔️
- [x] 토큰 만료 후 auth에 접근 동작 확인
- [x] (작동 제대로 될 시) 구현 지속
- [x] (작동 안 될 시) 에러 핸들링
