### ISSUE TITLE
주문내역상세(점주시점)

### ISSUE THREAD

**Issue by hmxb** [emartFresh/emart-fresh-back#52]
## Description 🗞️📕
점주가 회원들의 주문내역 상세를 볼 수 있게하기위해 만든 api

## Page 🖥️
OrderedProductController

## To-Do ✔️
- [x] orderedProductId를 받아서 주문내역product를 찾는다.
- [x] 주문내역 product에서 productId를 찾는다
- [x] productId로 제품 이름, 이미지url, 가격을 뽑아서 리스폰에 담아서 준다.
