### ISSUE TITLE
발주 신청시 유통기한 세팅하기

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh-back#67]
## Description 🗞️📕
발주 신청시 신청한 물품의 타입에 따라 각자 다른 유통기한을 세팅하기

## Page 🖥️
발주 신청
```
ManagerOrderController

@PostMapping("/add-manager-order")
public String saveManagerOrder(Authentication authentication, @RequestBody List<ManagerOrderDto> managerOrderDtoList) {
```

## To-Do ✔️
- [ ] 물품의 타입 검사
- [ ] 오늘 날짜 + 타입에 따른 유통기한으로 물품 유통기한 세팅하기
- [ ] 바뀐 값으로 저장 및 테스트

## notes 📝
팀원들이랑 타입별 유통기한 논의하기
